spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/owz-zhou/spring-cloud-repo
          searchPaths: spring-cloud-repo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
